# Generated by Django 5.0.6 on 2026-05-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(default='Driver Name', max_length=255)),
                ('carrier_name', models.CharField(default='Carrier Co.', max_length=255)),
                ('truck_number', models.CharField(default='TRK-001', max_length=100)),
                ('license_number', models.CharField(blank=True, default='', max_length=100)),
                ('home_terminal', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'driver_profile',
            },
        ),
        migrations.CreateModel(
            name='SavedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip_input', models.JSONField()),
                ('trip_plan', models.JSONField()),
            ],
            options={
                'db_table': 'saved_trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
